name: example-environment
channels:
  - conda-forge
  - bjodah
dependencies:
  - python=3.5
  - notebook
  - numpy
  - matplotlib
  - scipy
  - pycvodes
  - pycompilation
  - pycodeexport
  - pyodesys
